### ISSUE TITLE
The dataset can not be downloaded !!! giving error: {"code":"AccessDenied","message":"Your request is denied because there is an overdue bill of your account.","requestId":"fd3373c3-f10c-41cc-bf57-bda645ada1f7"}

### ISSUE THREAD

**Issue by 460130107** [baidu/DuReader#1]
{"code":"AccessDenied","message":"Your request is denied because there is an overdue bill of your account.","requestId":"fd3373c3-f10c-41cc-bf57-bda645ada1f7"}

**Comment by comeonfox** [comment]
Did you download from data/download.sh or from our web site(ai.baidu.com/broad) ?

**Comment by 460130107** [comment]
both giving the same error ..

**Comment by 460130107** [comment]
both giving the same error .. @comeonfox

**Comment by 460130107** [comment]
I can download it now.  thank you   @comeonfox
