### ISSUE TITLE
Code implementation different with paper in match layer

### ISSUE THREAD

**Issue by tsaikenyoo** [baidu/DuReader#11]
In file `match_layer.py` , class `MatchLSTMAttnCell`, function `__call__`

The variable `new_inputs` is computed as follows:
```
new_inputs = tf.concat([inputs, attended_context,
             inputs - attended_context, inputs * attended_context],
            -1)
```

However, I noticed that in the paper of match-LSTM, it should be

<img width="239" alt="2018-03-08 14 52 37" src="https://user-images.githubusercontent.com/28853070/37137365-63bbfe7c-22e0-11e8-9eb8-6f15eb9c12f7.png">

where, z_i corresponds to variable `new_inputs`, h_i^p corresponds to variable `inputs`, H^q * alpha_i^T corresponds to variable `attended_context`.

According to the algorithm in paper, the computation should be:

```
new_inputs = tf.concat([inputs, attended_context], -1)
```
So, I am wondering why `inputs - attended_context` and `inputs * attended_context` were involved.

@EastonWang

**Comment by EastonWang** [comment]
Thanks for your comment in details. Actually the authors of match-LSTM didn't describe this in the method section. Instead, they mentioned this trick in the section of experimental results, where the effect of `-elem` is shown in Table 4. So this implementation is the same as the best model in the original paper.  Though, we want to further clarify that our implementation is not strictly same as the original one. For example, we use bi-directional LSTM for passage and query encoding. But generally, we follow the ideas in Match-LSTM and implement the key components (e.g. match layer) similar as the paper.

**Comment by tsaikenyoo** [comment]
@EastonWang 
Thanks for replying. I guess I understand what you mean. But there is no `Table 4` either in paper [1] or [2]. So, maybe you are talking about a different paper??

[1]: Learning Natural Language Inference with LSTM
[2]: Machine Comprehension Using Match-LSTM and Answer Pointer

**Comment by EastonWang** [comment]
@tsaikenyoo I'm talking about paper [2], but the authors have updated this paper for the ICLR open review. You can refer to [this](https://openreview.net/pdf?id=B1-q5Pqxl), where the Table 4 is shown in page 7.

**Comment by tsaikenyoo** [comment]
Thank you for answering!
