### ISSUE TITLE
About the entity answers

### ISSUE THREAD

**Issue by ZacharyWuzh** [baidu/DuReader#13]
The test result of the baseline model all output a empty list for the entity_answers, so, for the evaluation of the entity question , which answer is used? The entity_answers or the answers ?

**Comment by lkliukai** [comment]
"answers" will be good, and the "answers" field is adopted to evaluate BLEU4 and ROUGE-L metrics.
"entity_answers" is the entity result for P/R/F-score on the Leaderboard, it does not participate in BLEU4 and ROUGE-L evaluation, for now.

**Comment by ZacharyWuzh** [comment]
thx




| |
吴宗恒
邮箱：henrywuzongheng@163.com
|

签名由 网易邮箱大师 定制

On 03/12/2018 20:53, lkliukai wrote:

"answers" will be good, and the "answers" field is adopted to evaluate BLEU4 and ROUGE-L metrics.
"entity_answers" is the entity result for P/R/F-score on the Leaderboard, it does not participate in BLEU4 and ROUGE-L evaluation, for now.
