### ISSUE TITLE
Error for preprocessing data

### ISSUE THREAD

**Issue by lreaderl** [baidu/DuReader#16]
In Readme, you said: 

> To preprocess the raw data, you should first segment 'question', 'title', 'paragraphs' and then store the segemented result into 'segmented_question', 'segmented_title', 'segmented_paragraphs' like the downloaded preprocessed data

Actually, the 'anwsers' should be segmented into 'segmented_anwsers' too, please notice that.

And , how long will it take for preprocessing data? I've run the python file for over 12 hours...

**Comment by lkliukai** [comment]
Yes indeed, for training data 'segmented_answers' is also required by preprocessing, we will fix that in README.md.
> And , how long will it take for preprocessing data? I've run the python file for over 12 hours...
The preprocessing algorithm is simply implemented and the complexity is high (is about O(n^3)),  and we recommend to preprocess the DuReader in a parallel way. For preprocessing is an one-time step before training, we will find a better way later.

**Comment by lreaderl** [comment]
Well, I hope you can find a better way as fast as you can~~~~~
