### ISSUE TITLE
Question about batch_size

### ISSUE THREAD

**Issue by cairoHy** [baidu/DuReader#19]
Question about batch_size:
The `run.py` file has `batch_size` term,and I set it to **64**. 
In `_train_epoch()` method, I insert the code below  to print run time shape:
```python
def _train_epoch(self, train_batches, **dropout_keep_prob):
# some code.......
        for bitx, batch in enumerate(train_batches, 1):
            feed_dict = {self.p: batch['passage_token_ids'],
                         self.q: batch['question_token_ids'],
                         self.p_length: batch['passage_length'],
                         self.q_length: batch['question_length'],
                         self.start_label: batch['start_id'],
                         self.end_label: batch['end_id'],
                         self.dropout_keep_prob: dropout_keep_prob}
            # inserted code
            p_shape,q_shape,sl_shape = self.sess.run([self.p, self.q, self.start_label], feed_dict)
            self.logger.info('p_shape {}\nq_shape {}\nsl_shape {}'.format(p_shape.shape,q_shape.shape,sl_shape.shape ))
```
The output is:
```bash
p_shape (320, 500)
q_shape (320, 12)
sl_shape (64,)
```
The first dimension of p and q and start_label is different, and first dimension of p and q are fixed number **320** for any batch_size setting in `run.py`.

**Comment by cairoHy** [comment]
supplement:
It seems for each mini-batch, question are replicated by `max_p_num` times, and `max_p_num` paragraphs are input so the first dim is `b*n`, and during decode process the first dimension is reshaped to concat different paragraphs.

**Comment by WhpHenry** [comment]
> supplement:
> It seems for each mini-batch, question are replicated by `max_p_num` times, and `max_p_num` paragraphs are input so the first dim is `b*n`, and during decode process the first dimension is reshaped to concat different paragraphs.

Sorry for question again

I noticed that `passage_encodes` would be reshape as `[batch_size, -1, 2 * self.hidden_size]`  in _decode() of rc_model.py.  

But each passage in training is built up by many `most_rela_para` paragraphs. 
what make me confused is why do not just take one paragraph which labeled by `answer_docs` as the passage  ??

**Comment by fooSynaptic** [comment]
> > supplement:
> > It seems for each mini-batch, question are replicated by `max_p_num` times, and `max_p_num` paragraphs are input so the first dim is `b*n`, and during decode process the first dimension is reshaped to concat different paragraphs.
> 
> Sorry for question again
> 
> I noticed that `passage_encodes` would be reshape as `[batch_size, -1, 2 * self.hidden_size]` in _decode() of rc_model.py.
> 
> But each passage in training is built up by many `most_rela_para` paragraphs.
> what make me confused is why do not just take one paragraph which labeled by `answer_docs` as the passage ??

i also found that was so wired
