### ISSUE TITLE
发现一个错误

### ISSUE THREAD

**Issue by bojone** [baidu/DuReader#2]
id为181573的question，bs_rank_pos＝2跟bs_rank_pos＝40的段落几乎是一样的，但是一个为select＝true，一个select＝false

当然我不大清楚这种错误是否普遍，仅此报告一下

**Comment by comeonfox** [comment]
感谢您的反馈。
is_selected 字段用来表示标注人员在撰写答案时是否直接参考了这篇文章。
is_selected=true 表示标注人员在撰写答案时部分或全部的用到了这篇文章；is_selected=false表示标注人员在撰写答案的时候没有直接使用本篇文章中的内容，但不表示本篇文章一定不包含答案。
我们会尽快将这个字段的详细解释更新到数据的文档中。

**Comment by comeonfox** [comment]
'is_selected' indicates whether the annotators referenced the corresponding passage or not when they conclude and write the answers.
'is_selected=true' means the annotator uses part of or all of the corresponding passage when writing answers; 'is_selected=false' means the annotator doesn't use content of the corresponding passage, but this doesn't mean the passage does not contain the answers.
We will update our documents soon to clarify the meaning of this field.
