### ISSUE TITLE
run TensorFlow的时候Utils下缺少文件

### ISSUE THREAD

**Issue by 495783410** [baidu/DuReader#21]
run TensorFlow的时候Utils下缺少文件
from utils import compute_bleu_rouge
from utils import normalize

**Comment by lkliukai** [comment]
Please run 'sh download_thirdparty.sh' to get the third-party libraries to fix that.

**Comment by AntoineSimoulin** [comment]
the compute_bleu_rouge and normalize functions are located under ./utils/dureader_eval.py. There is an import correction to make in ./tensorflow/run.py

from utils.dureader_eval import compute_bleu_rouge
from utils.dureader_eval import normalize
