### ISSUE TITLE
About Match-LSTM code

### ISSUE THREAD

**Issue by bestbzw** [baidu/DuReader#22]
hi
when i read the code ./tensorflow/nn_layers/match_layer.py, the class MatchLSTMAttnCell.
I found the you concat H^p ,H^q\alpha and H^p-H^q\alpha, H^p*H^q\alpha as the input of Match-LSTM , but the model proposed by Wang only concat  H^p and H^q\alpha as the new input of Match-LSTM.
Could u tell me why did you make such a change.

**Comment by lkliukai** [comment]
Inspired by other research works, we tried such a tiny change and  observed some improvements on test sets. As a result, we kept the change in the code.

**Comment by bestbzw** [comment]
thanks for the fast response!
