### ISSUE TITLE
用demo数据运行paddle的问题

### ISSUE THREAD

**Issue by urcllr** [baidu/DuReader#24]
运行paddle的infer这步，需要用到preprocessed/testnet下的数据
![dureader](https://user-images.githubusercontent.com/38638662/39356435-95792f14-4a42-11e8-8f2b-62020b7ba85c.png)

但github代码中并没有demo对应的preprocessed数据。我按Preprocess the Data那节的命令来生成testnet预处理数据出错（trainset和devset成功，只有testset失败。经查search.test.json的确没有segmented_answers键）
![paddle-demo-preprocess](https://user-images.githubusercontent.com/38638662/39356541-d47169c0-4a42-11e8-921b-80d1dc9854ab.png)

这样导致用demo的数据无法执行paddle infer这步，执行完后models底下的infer目录是空的。

**Comment by lkliukai** [comment]
For convenience, please use preprocessed version of our dataset, or segment questions, documents and references by yourself and provide "segmented_*" field for the preprocess script.

**Comment by urcllr** [comment]
不好意思，是我昨天没理解透preprocess个章节，看漏了要自己先分词放入对应的segmented字段。
今天再看了下载的raw和preprocessed的头几行格式，大概总结出有以下的字段：
RAW
{
	question,question_type,fact_or_option,question_id,
	documents[{title,bs_rank_pos？,is_selected？,paragraphs[]}],
	entity_answers[],
	answers[]
}

PREPROCESSED
{
	question,question_type,fact_or_option,question_id,
	documents[{title,bs_rank_pos,is_selected,paragraphs[],+most_related_para？,+segmented_title[对title分词],+segmented_paragraphs[对paragraphs分词]}],
	answers[],
	+answer_spans[],？
	+fake_answers[],？
	+segmented_answers[对answers分词],
	+answer_docs[],？
	+segmented_question[对question分词],
	+match_scores[]？,
	+yesno_type？
}

有几个问题想了解一下：
1. 打？的那些字段代表什么意义？
2. RAW里面的answers、entity_answers、documents.paragraphs似乎都是答案，有什么区别？
3. PREPROCESSED里面+开头的字段，除了segmented_开头外，还有哪些是额外添加的（即不是preprocess.py生成的）？
