### ISSUE TITLE
paddle infer mode KeyError: 'answer_docs'

### ISSUE THREAD

**Issue by yangze01** [baidu/DuReader#28]
bash run_demo.sh test_bidaf_demo bidaf infer --testset ../data/preprocessed/testset/search.test.json
tensorflow版本没有问题，可以跑通。
paddlepaddle版本，训练集和验证集因为有ground_truth, 所以存在"answer_docs"。但是在测试集中没有ground_truth，所以就不存在“answer_docs”。但是在paddle版本的dataset.py中确实存在json解析，必须要"answer_docs"字段。是我需要进一步预处理一下数据还是说要在测试的时候改这部分代码？

**Comment by lkliukai** [comment]
>是我需要进一步预处理一下数据还是说要在测试的时候改这部分代码？

Yes, or you just forge one to fool the system.
