### ISSUE TITLE
The implementation of BiDAF is not exactly same as the one in the original paper

### ISSUE THREAD

**Issue by xbainbain** [baidu/DuReader#30]
For the calculation of similarity matrix, 
```python
sim_matrix = tf.matmul(passage_encodes, question_encodes, transpose_b=True)
```
This is a simple dot product. But the original paper choose
<img width="310" alt="untitled" src="https://user-images.githubusercontent.com/24229049/41028923-064dad8a-69ad-11e8-9e2a-6b0b74b34a5e.png">
where` h` is the passage representation and `u` is the question representation.
This maybe not a big problem, but it may still cause some difference.

**Comment by lkliukai** [comment]
Thanks for your comment! And we have to clarify that our implementation is not strictly same as the original one. And for the  similarity matrix, we indeed select a simplified implementation. It may cause some differences, but we do not investigate significant performance difference for now.
