### ISSUE TITLE
About some hyperparams in the paper https://arxiv.org/pdf/1711.05073.pdf

### ISSUE THREAD

**Issue by zhangkaixu** [baidu/DuReader#32]
Is the performance reported in the paper measured by using this repo?
How about some other hyperparams that this paper did not mention, such as weight_decay and dropout_keep_prob?
Thank you

**Comment by lkliukai** [comment]
Yes it is! And part of detail parameters we have lost, but lucky we do remember the `weight_decay=3e-7` and `dropout_keep_prob=0.9`.
