### ISSUE TITLE
python3 unicodedecodeerror: ascii codec can't

### ISSUE THREAD

**Issue by fendouai** [baidu/DuReader#37]
![wechatimg1161](https://user-images.githubusercontent.com/6284532/47002522-c90d7200-d15f-11e8-9024-da96072ae9ef.jpeg)

**Comment by lkliukai** [comment]
Thanks for your feedback! The system is not ready to support Python 3. The error suggest an decoding failure of input data, a potential fix method is to convert the input encoding to ASCII.
