### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 4803: ordinal not in range(128)

### ISSUE THREAD

**Issue by 1119093254** [baidu/DuReader#38]
![image](https://user-images.githubusercontent.com/19251747/50078294-8cbec680-0221-11e9-8a73-d8bfcb20178f.png)

**Comment by lkliukai** [comment]
Did you follow the running instruction? The error usually occurs when the system reading a ascii file as utf-8 format.
