### ISSUE TITLE
关于实现细节

### ISSUE THREAD

**Issue by demeiyan** [baidu/DuReader#39]
![co2wkmz8pl0p61wn 8u9 fb](https://user-images.githubusercontent.com/12872156/50389765-22e67580-0769-11e9-89af-1bafa5a22566.png)
论文中S是这样求的，而这个实现中只是将p和q进行简单的相乘？这是为什么？还有论文中Modeling Layer是两层双向LSTM为什么这里只用了一层？

**Comment by lkliukai** [comment]
Thank you for your comment! And for this question pls refer to #30 .
