### ISSUE TITLE
I was implemented the dureader to recognize the story name from a long text but the result is so wired

### ISSUE THREAD

**Issue by fooSynaptic** [baidu/DuReader#41]
I inspected the json format and prepared with labeled answers.
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/19420328/53141353-bbaf3b00-35ca-11e9-8259-c9c0e07b866f.png">

**Comment by fooSynaptic** [comment]
the train file look like 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/19420328/53141603-ab4b9000-35cb-11e9-9b01-c1606f13193a.png">

and the prepare fns behave like:
`res = train_json_prepare(raw_paragraph[i], '今天听什么长篇评书？', \
            '今天听什么长篇评书？', ans_span[i])`

**Comment by lkliukai** [comment]
I am not sure about the details of your task, and what about the results when you treat your task as an entity tagging task?

**Comment by fooSynaptic** [comment]
> I am not sure about the details of your task, and what about the results when you treat your task as an entity tagging task?

@lkliukai I do not think the NER can replace the reading comprehension task

**Comment by lkliukai** [comment]
> > I am not sure about the details of your task, and what about the results when you treat your task as an entity tagging task?
> 
> @lkliukai I do not think the NER can replace the reading comprehension task

No, I don't think so. NER is only a part of QA task.

**Comment by fooSynaptic** [comment]
> > > I am not sure about the details of your task, and what about the results when you treat your task as an entity tagging task?
> > 
> > 
> > @lkliukai I do not think the NER can replace the reading comprehension task
> 
> No, I don't think so. NER is only a part of QA task.

learnning task is not only result generation method, i understand that you point out NER produce result in a similar form with QA, but their optimize target is very different
