### ISSUE TITLE
About the preprocessed data

### ISSUE THREAD

**Issue by jose77** [baidu/DuReader#5]
I see in the preprocessed data, there are several answers in the field of "answers", but only one element in "answer_docs" and "answer_spans", which answer should I choose? I also want to know does the element in "answer_docs" mean the index of selected passages? Thank you.

**Comment by comeonfox** [comment]
Thanks for your feedback.
"answer_docs", "most_related_paragraph", "answer_spans" are used together to target the location of any of answers in the field "answers"， the location is needed for many popular methods that take advantage of pointer net which models the location of the answer.
As you can see, although the annotators generated up to 3 answers for every question, we only targeted the one that matches best in our given documents, and our model tries to find that one answer and ignores the rest. But this is only our strategy to make the data convenient for training, you can develop your own strategy according to different cases.
"answer_docs" is  the index of documents that contains the answer text, "most_related_paragraph" is the paragraph index of "answer_docs" that contains the answer text and "answer_spans" describes the exact start and end position on "most_related_paragraph" that matches answer best.

**Comment by jose77** [comment]
Thanks for your answer.
But I think there are examples which "answer_docs" do not match selected document index.
For instance:
In processed/devset/zhidao.dev.json, question_id 186582:
`{"documents": [{"is_selected": true, "title": "广联达正版软件多少钱", "most_related_para": 0, "segmented_title": ["广联达", "正版", "软件", "多少", "钱"], "segmented_paragraphs": [["现在", "一", "个", "建筑", "的", "图形", "算", "量", "就要", "8000", "元", "左右", "。", "三合一", "啥", "的", "一万多", "妥妥", "的", "。"]], "paragraphs": ["现在一个建筑的>图形算量就要8000元左右。三合一啥的一万多妥妥的。"], "bs_rank_pos": 5}`
`"answer_docs": [0]`

**Comment by comeonfox** [comment]
The answer_docs[0] does contain the right answer, which is the second item in 'answers'. Please make your question more clear, thank you.
