### ISSUE TITLE
data/download.sh 里的连接已经失效了

### ISSUE THREAD

**Issue by memeda** [baidu/DuReader#60]
顺便吐槽下 ai.baidu.com ， 跳转不带tag，从DuReader里点击download，弹出来的页面竟然是download页面里的DuConv

不知道找谁反馈

**Comment by xybai** [comment]
同学，关于这个有什么更新么

**Comment by memeda** [comment]
@xybai  😃 ,发现你也问了同样的问题，不用这个download脚本，可以自己去下哈， 点repo介绍那个链接就可以下了，或者这个链接： http://ai.baidu.com/broad/download?dataset=dureader 下下来自己解压，能够对上

**Comment by xybai** [comment]
> @xybai 😃 ,发现你也问了同样的问题，不用这个download脚本，可以自己去下哈， 点repo介绍那个链接就可以下了，或者这个链接： http://ai.baidu.com/broad/download?dataset=dureader 下下来自己解压，能够对上

@memeda  同学，我这边还是不行，下载非常得慢
![image](https://user-images.githubusercontent.com/10529016/60807792-2f886380-a1b9-11e9-9750-59a804e64b1d.png)

**Comment by memeda** [comment]
我这边可以呢，我传到百度网盘给你？ 不知道犯法不 😂

**Comment by xybai** [comment]
> 我这边可以呢，我传到百度网盘给你？ 不知道犯法不 😂

@memeda 啊，为啥呢，难道是因为我的网络在墙外，同学，我晚上再试下，不翻墙下载看看，如果还不行我再想想办法，再不行的话，再想想办法看能不能麻烦你发给我吧，麻烦了，感谢！

**Comment by memeda** [comment]
嗯嗯，有可能呢，你不翻墙下试试~ 我这边看下载源是baidu beijing的cdn，我估计墙外没有cdn，所以没啥速度

**Comment by xybai** [comment]
> 嗯嗯，有可能呢，你不翻墙下试试~ 我这边看下载源是baidu beijing的cdn，我估计墙外没有cdn，所以没啥速度

嗯嗯，好哒，我再试试看，麻烦啦

**Comment by memeda** [comment]
哈哈，没事~ 下不了再说哈

**Comment by xybai** [comment]
> 哈哈，没事~ 下不了再说哈

嗯嗯

**Comment by lkliukai** [comment]
The download url have been update!
