### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by cairoHy** [baidu/DuReader#9]
Unresolved reference **brc_eval** and **find_answer** in utils/baseline_eval.py, 27 line.

**Comment by comeonfox** [comment]
Thanks for your feedback.
`utils/baseline_eval.py` is used to do certain statistics for private usage, we put it under `utils` folder only as a code example to show logics of some common metrics, so it can't run successfully. For model evaluation, we recommend you to use `utils/dureader_eval.py`.
To eliminate users' doubts, I will remove this script soon.
